spring.application.name=task




spring.datasource.url = jdbc:postgresql://localhost:5432/himalayan_task_db
spring.datasource.username= postgres
spring.datasource.password= postgres
spring.datasource.driverClassName= org.postgresql.Driver


server.port = 8081
spring.jpa.hibernate.ddl-auto = update
