spring.application.name=task




spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${POSTGRES_DB:himalayan_task_db}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}

spring.datasource.driverClassName= org.postgresql.Driver

server.port=${SPRING_PORT:8081}


spring.jpa.hibernate.ddl-auto = update
